### ISSUE TITLE
Update docs formatting

### ISSUE THREAD

**Issue by matthew-powers-db** [MrPowers/chispa#138]
```
- pymdownx.highlight:
  anchor_linenums: true
  line_spans: __span
  pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
```

This snippet should be added to quinn and (maybe) chispa. Otherwise syntax highlighting in docs is not working
