### ISSUE TITLE
Trying to use Chispa in a new environment with Spark 2.4 and it installs Spark 3.0. Can this behaviour be made optional or does Chispa definitely need 3.0?

### ISSUE THREAD

**Issue by digrks** [MrPowers/chispa#3]

**Comment by digrks** [comment]
This behaviour is quite annoying as at the moment I have to install pyspark 2.4 afterwards.
Happy to contribute if someone can point me in the right direction?

**Comment by MrPowers** [comment]
@digrks - thanks for opening this issue.

Chispa requires pyspark = ">2.0.0", see [the pyproject.toml file](https://github.com/MrPowers/chispa/blob/master/pyproject.toml).

Chispa can work with either PySpark 2.4 or PySpark 3.0.  How to configure your project dependencies depends on if you're using Poetry, Conda, pipenv, or vanilla pip.  This post explains how to [create a PySpark project with Poetry](https://mungingdata.com/pyspark/poetry-dependency-management-wheel/).  You could add something like this in your pyproject.toml file if you're using poetry:

```toml
[tool.poetry.dependencies]
python = "^3.7"
pyspark = "^2.4.6"
quinn = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
chispa = "^0.4.0"
```

Here's [an example repo that uses this exact setup](https://github.com/MrPowers/pysparktestingexample/blob/master/pyproject.toml).

Let me know if you're able to figure this out!
